import type { Product, Order, Employee, QualityCheck, Task, DemandPrediction } from './types'

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Premium Cotton Fabric',
    category: 'Cotton',
    description: 'High-quality 100% cotton fabric, suitable for garments',
    price: 450,
    stock: 1200,
    minStock: 200,
    unit: 'meters',
  },
  {
    id: 'p2',
    name: 'Silk Blend Textile',
    category: 'Silk',
    description: 'Luxurious silk blend fabric for premium wear',
    price: 1200,
    stock: 350,
    minStock: 100,
    unit: 'meters',
  },
  {
    id: 'p3',
    name: 'Polyester Mix',
    category: 'Synthetic',
    description: 'Durable polyester fabric for industrial use',
    price: 280,
    stock: 2500,
    minStock: 500,
    unit: 'meters',
  },
  {
    id: 'p4',
    name: 'Linen Fabric',
    category: 'Linen',
    description: 'Natural linen fabric, breathable and elegant',
    price: 680,
    stock: 180,
    minStock: 150,
    unit: 'meters',
  },
  {
    id: 'p5',
    name: 'Denim Material',
    category: 'Cotton',
    description: 'Heavy-duty denim for jeans and workwear',
    price: 520,
    stock: 800,
    minStock: 200,
    unit: 'meters',
  },
  {
    id: 'p6',
    name: 'Velvet Fabric',
    category: 'Luxury',
    description: 'Soft velvet fabric for upholstery and fashion',
    price: 950,
    stock: 120,
    minStock: 50,
    unit: 'meters',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'o1',
    customerId: 'c1',
    customerName: 'Fashion Hub Ltd',
    products: [
      { productId: 'p1', productName: 'Premium Cotton Fabric', quantity: 500, price: 450 },
      { productId: 'p5', productName: 'Denim Material', quantity: 300, price: 520 },
    ],
    status: 'processing',
    totalAmount: 381000,
    createdAt: '2026-03-01',
    assignedEmployee: 'e1',
  },
  {
    id: 'o2',
    customerId: 'c2',
    customerName: 'Elite Garments',
    products: [
      { productId: 'p2', productName: 'Silk Blend Textile', quantity: 200, price: 1200 },
    ],
    status: 'quality-check',
    totalAmount: 240000,
    createdAt: '2026-03-03',
    assignedEmployee: 'e2',
    qualityScore: 92,
  },
  {
    id: 'o3',
    customerId: 'c3',
    customerName: 'Global Textiles Inc',
    products: [
      { productId: 'p3', productName: 'Polyester Mix', quantity: 1000, price: 280 },
      { productId: 'p4', productName: 'Linen Fabric', quantity: 150, price: 680 },
    ],
    status: 'pending',
    totalAmount: 382000,
    createdAt: '2026-03-05',
  },
  {
    id: 'o4',
    customerId: 'c1',
    customerName: 'Fashion Hub Ltd',
    products: [
      { productId: 'p6', productName: 'Velvet Fabric', quantity: 80, price: 950 },
    ],
    status: 'shipped',
    totalAmount: 76000,
    createdAt: '2026-02-28',
    assignedEmployee: 'e3',
    qualityScore: 98,
  },
]

export const mockEmployees: Employee[] = [
  {
    id: 'e1',
    name: 'Rajesh Kumar',
    email: 'rajesh@sathiyatex.com',
    phone: '+91 98765 43210',
    department: 'Production',
    skills: ['Weaving', 'Quality Control', 'Machine Operation'],
    workload: 75,
    joinDate: '2022-06-15',
    status: 'active',
  },
  {
    id: 'e2',
    name: 'Priya Sharma',
    email: 'priya@sathiyatex.com',
    phone: '+91 98765 43211',
    department: 'Quality Assurance',
    skills: ['Quality Inspection', 'Documentation', 'Testing'],
    workload: 60,
    joinDate: '2021-03-20',
    status: 'active',
  },
  {
    id: 'e3',
    name: 'Arun Patel',
    email: 'arun@sathiyatex.com',
    phone: '+91 98765 43212',
    department: 'Shipping',
    skills: ['Logistics', 'Packaging', 'Inventory'],
    workload: 45,
    joinDate: '2023-01-10',
    status: 'active',
  },
  {
    id: 'e4',
    name: 'Lakshmi Devi',
    email: 'lakshmi@sathiyatex.com',
    phone: '+91 98765 43213',
    department: 'Production',
    skills: ['Dyeing', 'Finishing', 'Color Matching'],
    workload: 80,
    joinDate: '2020-11-05',
    status: 'busy',
  },
  {
    id: 'e5',
    name: 'Suresh Menon',
    email: 'suresh@sathiyatex.com',
    phone: '+91 98765 43214',
    department: 'Maintenance',
    skills: ['Machine Repair', 'Electrical', 'Preventive Maintenance'],
    workload: 30,
    joinDate: '2024-02-01',
    status: 'active',
  },
]

export const mockQualityChecks: QualityCheck[] = [
  {
    id: 'qc1',
    orderId: 'o1',
    employeeId: 'e2',
    checkDate: '2026-03-04',
    score: 95,
    defectsFound: 2,
    notes: 'Minor color variations in batch 3, corrected.',
    status: 'passed',
  },
  {
    id: 'qc2',
    orderId: 'o2',
    employeeId: 'e2',
    checkDate: '2026-03-05',
    score: 92,
    defectsFound: 5,
    notes: 'Some thread inconsistencies, within acceptable range.',
    status: 'passed',
  },
  {
    id: 'qc3',
    orderId: 'o4',
    employeeId: 'e2',
    checkDate: '2026-03-01',
    score: 98,
    defectsFound: 0,
    notes: 'Excellent quality, no defects found.',
    status: 'passed',
  },
]

export const mockTasks: Task[] = [
  {
    id: 't1',
    orderId: 'o1',
    employeeId: 'e1',
    title: 'Prepare Cotton Fabric Order',
    description: 'Cut and prepare 500m premium cotton fabric for Fashion Hub Ltd',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2026-03-08',
  },
  {
    id: 't2',
    orderId: 'o2',
    employeeId: 'e2',
    title: 'Quality Inspection - Silk Order',
    description: 'Perform final quality check on silk blend order',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2026-03-06',
  },
  {
    id: 't3',
    orderId: 'o3',
    employeeId: 'e4',
    title: 'Dye Polyester Batch',
    description: 'Apply color treatment to polyester order',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-03-10',
  },
  {
    id: 't4',
    orderId: 'o4',
    employeeId: 'e3',
    title: 'Ship Velvet Order',
    description: 'Package and ship velvet fabric to Fashion Hub Ltd',
    priority: 'low',
    status: 'completed',
    dueDate: '2026-03-02',
  },
]

export const mockDemandPredictions: DemandPrediction[] = [
  {
    productId: 'p1',
    productName: 'Premium Cotton Fabric',
    currentStock: 1200,
    predictedDemand: 1800,
    recommendation: 'Order 800 meters to meet projected demand',
    confidence: 87,
  },
  {
    productId: 'p2',
    productName: 'Silk Blend Textile',
    currentStock: 350,
    predictedDemand: 280,
    recommendation: 'Stock levels adequate for next quarter',
    confidence: 92,
  },
  {
    productId: 'p4',
    productName: 'Linen Fabric',
    currentStock: 180,
    predictedDemand: 320,
    recommendation: 'Critical: Order 200 meters immediately',
    confidence: 78,
  },
  {
    productId: 'p6',
    productName: 'Velvet Fabric',
    currentStock: 120,
    predictedDemand: 150,
    recommendation: 'Consider ordering 50 meters',
    confidence: 85,
  },
]
